name: Naivebmcar1gfp
channels:
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - anyio=3.5.0=py37hecd8cb5_0
  - appnope=0.1.2=py37hecd8cb5_1001
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37hca72f7f_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h9ed2024_1003
  - ca-certificates=2022.2.1=hecd8cb5_0
  - certifi=2021.10.8=py37hecd8cb5_2
  - cffi=1.15.0=py37hc55c11b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py37hf6deb26_0
  - debugpy=1.5.1=py37he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py37hecd8cb5_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37hecd8cb5_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.2.9=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libsodium=1.0.18=h1de35cc_0
  - mistune=0.8.4=py37h1de35cc_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - notebook=6.4.8=py37hecd8cb5_0
  - openssl=1.1.1m=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - python=3.7.11=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=22.3.0=py37he9d5cce_2
  - readline=8.1.2=hca72f7f_1
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py37hecd8cb5_1
  - sqlite=3.37.2=h707629a_0
  - tk=8.6.11=h7bc2e8c_0
  - tornado=6.1=py37h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=0.58.0=py37hecd8cb5_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py37hecd8cb5_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h4dc903c_4
  - pip
  - pip:
    - anndata==0.7.8
    - cached-property==1.5.2
    - cycler==0.11.0
    - cython==0.29.27
    - entrypoints==0.4
    - fonttools==4.29.1
    - h5py==3.6.0
    - importlib-metadata==4.11.2
    - importlib-resources==5.4.0
    - ipykernel==6.9.1
    - ipython==7.32.0
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-core==4.9.2
    - kiwisolver==1.3.2
    - llvmlite==0.38.0
    - markupsafe==2.1.0
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - natsort==8.1.0
    - nbconvert==6.4.2
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - numba==0.55.1
    - numexpr==2.8.1
    - numpy==1.21.5
    - pandas==1.3.5
    - patsy==0.5.2
    - pillow==9.0.1
    - pip==22.0.3
    - prompt-toolkit==3.0.28
    - pynndescent==0.5.6
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytz==2021.3
    - scanpy==1.8.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - sinfo==0.3.4
    - statsmodels==0.13.2
    - stdlib-list==0.8.0
    - tables==3.7.0
    - terminado==0.13.2
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tqdm==4.63.0
    - typing-extensions==4.1.1
    - umap-learn==0.5.2
    - webencodings==0.5.1
    - wget==3.2
    - xlrd==1.2.0
prefix: /Users/Kat/opt/anaconda3/envs/Naivebmcar1gfp
